# -*- coding: utf-8 -*-
"""Assignment (Python Fundamentals)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fwgd5AWCnS3ZQIDtbsyDbn4W9MaE_tL
"""

#Task 1: Data Types and Variables

# Create variables to store the following data types: integer, float, string, boolean.
# Print the types of these variables using the type() function.
# Perform basic arithmetic operations (addition, subtraction, etc.) with the numerical variables.


# 1. Creating variables
my_integer = 80
my_float = 53.14
my_string = "Hello World!"
my_boolean = True

# 2. Printing Variable Types:
print("Integer type:", type(my_integer))
print("Float type:", type(my_float))
print("String type:", type(my_string))
print("Boolean type:", type(my_boolean))

#3. Performing Arithmetic Operations:

r_addition = my_integer + my_float
r_subtraction = my_integer - my_float
r_multiplication = my_integer * my_float
r_division = my_integer / my_float

print("Addition:", r_addition)
print("Subtraction:", r_subtraction)
print("Multiplication:", r_multiplication)
print("Division:", r_division)

#Task 2: Control Flow (if/else)

# Write a program that takes a number as input.
# Use an if/else statement to determine if the number is even or odd and print the result.


number = int(input("Enter a number: "))


if number % 2 == 0:
  print(f"{number} is even.")

else:
  print(f"{number} is odd.")

# Task 3: Strings and Manipulation

# Create a string variable containing a sentence.
# Use string methods to:
# Convert the sentence to uppercase and lowercase.
# Split the sentence into a list of words.
# Find the length of the sentence.
# Replace a specific word in the sentence with another word.



# Create a string sentence
sentence = "This is a test sentence."

# Uppercase and lowercase
uppercase_sentence = sentence.upper()
lowercase_sentence = sentence.lower()

# Split into words (list)
words = sentence.split()

# Length of the sentence
sentence_length = len(sentence)

# Replace a word
new_sentence = sentence.replace("test", "replaced")

# Print results
print(f"Original sentence: {sentence}")
print(f"Uppercase: {uppercase_sentence}")
print(f"Lowercase: {lowercase_sentence}")
print(f"Words as list: {words}")
print(f"Length of sentence: {sentence_length}")
print(f"Sentence with replaced word: {new_sentence}")

# Task 4: Loops (for/while)

# Use a for loop to iterate over the elements in a list of numbers and print each number multiplied by 2.
# Use a while loop to calculate the sum of numbers from 1 to 10.


# for loop - multiply by 2
numbers = [1, 2, 3, 4, 5]

for x in numbers:
  doubled_number = x * 2
  print(f"{x} x 2 = {doubled_number}")


  # while loop - sum of numbers 1 to 10
total_sum = 0
current_number = 1

while current_number <= 10:
  total_sum += current_number
  current_number += 1

print(f"Sum of numbers from 1 to 10: {total_sum}")

#Task 5: Lists and List Comprehensions

# Create a list of your favorite fruits.
# Use a list comprehension to create a new list containing the lengths of each fruit.
# Append a new fruit to the original list.
# Sort the list alphabetically.


# Favorite fruits
fruits = ["apple", "banana", "orange"]

# Lengths using list comprehension
fruit_lengths = [len(fruit) for fruit in fruits]
print("lenth of each fruit",fruit_lengths)

# Append a new fruit
fruits.append("mango")
print("Adding new fruit in list", fruits)

# Sort fruits alphabetically
fruits.sort()
print("List after sorting", fruits)

#Task 6: Dictionaries

# Create a dictionary to store information about a book (title, author, year).
# Access and print individual values from the dictionary.
# Add a new key-value pair to the dictionary (e.g., genre).
# Use a loop to iterate over the dictionary's items and print them.


# Book information
book_title = "Pride and Prejudice"
book_author = "Jane Austen"
book_year = 1813

# Printing Book information
book_info = {
  "Title": book_title,
  "Author": book_author,
  "Year Published": book_year
}

print(f" {book_info}")


# Add a new piece of information (like putting a new item in the box)
book_info["Genre"] = "Romance"

# Print all information together (like looking at everything in the box)
for key, value in book_info.items():
  print(f"{key}: {value}")